[env:esp32-c3]
platform = espressif32
board = airm2m_core_esp32c3
framework = arduino

monitor_speed = 115200

lib_deps = 
    hoeken/PsychicHttp
    nanopb/Nanopb
    bblanchon/ArduinoJson@^7.4.3

build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Iproto

board_build.partitions = littlefs.csv
board_build.filesystem = littlefs

extra_scripts = pre:web_content.py

custom_nanopb_protos =
    +<proto/simple.proto>
