[env:esp32-c3]
platform = espressif32
board = airm2m_core_esp32c3
framework = arduino

monitor_speed = 115200

lib_deps = 
    hoeken/PsychicHttp
    nanopb/Nanopb

build_flags =
    -DCORE_DEBUG_LEVEL=5
    -Iproto

board_build.partitions = littlefs.csv
board_build.filesystem = littlefs

extra_scripts = pre:web_content.py
