/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MEASURE_PB_H_INCLUDED
#define PB_MEASURE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MeasureData {
    float current;
    float voltage;
    float power;
    float frequency;
    float power_usage;
    bool sd_logs_enable;
    bool wifi_enable;
} MeasureData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MeasureData_init_default                 {0, 0, 0, 0, 0, 0, 0}
#define MeasureData_init_zero                    {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MeasureData_current_tag                  1
#define MeasureData_voltage_tag                  2
#define MeasureData_power_tag                    3
#define MeasureData_frequency_tag                4
#define MeasureData_power_usage_tag              5
#define MeasureData_sd_logs_enable_tag           6
#define MeasureData_wifi_enable_tag              7

/* Struct field encoding specification for nanopb */
#define MeasureData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    power,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    frequency,         4) \
X(a, STATIC,   SINGULAR, FLOAT,    power_usage,       5) \
X(a, STATIC,   SINGULAR, BOOL,     sd_logs_enable,    6) \
X(a, STATIC,   SINGULAR, BOOL,     wifi_enable,       7)
#define MeasureData_CALLBACK NULL
#define MeasureData_DEFAULT NULL

extern const pb_msgdesc_t MeasureData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MeasureData_fields &MeasureData_msg

/* Maximum encoded size of messages (where known) */
#define MEASURE_PB_H_MAX_SIZE                    MeasureData_size
#define MeasureData_size                         29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
