/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_SIMPLE_PB_H_INCLUDED
#define PB_PROTO_SIMPLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorData {
    float temperature;
    float humidity;
    uint32_t timestamp;
    char sensor_id[32];
} SensorData;

typedef struct _SensorResponse {
    bool success;
    char message[64];
    bool has_data;
    SensorData data;
} SensorResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorData_init_default                  {0, 0, 0, ""}
#define SensorResponse_init_default              {0, "", false, SensorData_init_default}
#define SensorData_init_zero                     {0, 0, 0, ""}
#define SensorResponse_init_zero                 {0, "", false, SensorData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData_temperature_tag               1
#define SensorData_humidity_tag                  2
#define SensorData_timestamp_tag                 3
#define SensorData_sensor_id_tag                 4
#define SensorResponse_success_tag               1
#define SensorResponse_message_tag               2
#define SensorResponse_data_tag                  3

/* Struct field encoding specification for nanopb */
#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         3) \
X(a, STATIC,   SINGULAR, STRING,   sensor_id,         4)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL

#define SensorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              3)
#define SensorResponse_CALLBACK NULL
#define SensorResponse_DEFAULT NULL
#define SensorResponse_data_MSGTYPE SensorData

extern const pb_msgdesc_t SensorData_msg;
extern const pb_msgdesc_t SensorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorData_fields &SensorData_msg
#define SensorResponse_fields &SensorResponse_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_SIMPLE_PB_H_MAX_SIZE               SensorResponse_size
#define SensorData_size                          49
#define SensorResponse_size                      118

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
